INSERT INTO COURSE(COURSE_ID,COURSE_NAME,COURSE_DESC) VALUES (21,'MA','MASTER IN ARTS');
INSERT INTO COURSE(COURSE_ID,COURSE_NAME,COURSE_DESC) VALUES (22,'BA','BACHLOR IN ARTS');
INSERT INTO COURSE(COURSE_ID,COURSE_NAME,COURSE_DESC) VALUES (23,'MCOM','MASTER IN COMERSE');

--INSERT INTO STUDENT(STUDENT_ID,STUDENT_NAME,ADDRESS,COURSE_ID) VALUES (100,'ABC','Bangalore,bbmp office',21);
--INSERT INTO STUDENT(STUDENT_ID,STUDENT_NAME,ADDRESS,COURSE_ID) VALUES (101,'ABC','Balgaon,office',22);
--INSERT INTO STUDENT(STUDENT_ID,STUDENT_NAME,ADDRESS,COURSE_ID) VALUES (102,'ABC','Bangalore,HSR',23);
